In [1]:
%reload_ext autoreload

import pandas as pd
import sys
import os
sys.path.append("..")

from magni_dash.config.constants import EYT_SAMPLES_PATH
from magni_dash.data_preprocessing.load import load_df

In [2]:
EYT_SAMPLES_PATH

'/home/tmr/Documents/PhD/My_PhD/Magni/magni-dash-samples/sync'

In [3]:
PARTICIPANT = 3

In [4]:
path = os.path.join(EYT_SAMPLES_PATH, f"PT{PARTICIPANT}")

In [5]:
eyt_fn = "PT3_SCA.csv"
traj_fn = "Qualisys_270922_SC6A_H1_P1_pp.tsv"

In [16]:
eyt_df = pd.read_csv(os.path.join(path, eyt_fn), index_col="QTMFrameNr")

In [17]:
eyt_df

,TobiiFrameNr,VideoFrameNr,EyeMovementType,2DX,2DY,3DX,3DY,3DZ
QTMFrameNr,,,,,,,,
1,4773.0,401.0,Fixation,788.0,840.0,78.0496,-129.4320,434.3249
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4780.0,NaN,Fixation,780.0,833.0,79.0291,-121.6220,418.7168
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4785.0,402.0,Fixation,784.0,830.0,72.0942,-111.9771,390.4765
...,...,...,...,...,...,...,...,...
23852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23853,0.0,NaN,Invalid,0.0,0.0,0.0000,0.0000,0.0000
23854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23855,0.0,NaN,Invalid,0.0,0.0,0.0000,0.0000,0.0000
23856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
traj_df = load_df(
    df_path=os.path.join(path, traj_fn),
    sep="\t",
    header=11,
    index_col="Frame",
)

In [24]:
traj_df = traj_df.dropna(axis=1, how='all')

In [25]:
traj_df

,Time,DARKO_Robot - 1 X,DARKO_Robot - 1 Y,DARKO_Robot - 1 Z,DARKO_Robot - 2 X,DARKO_Robot - 2 Y,DARKO_Robot - 2 Z,DARKO_Robot - 3 X,DARKO_Robot - 3 Y,DARKO_Robot - 3 Z,...,DARKO_Robot - 7 Z,Helmet_1 - 1 X,Helmet_1 - 1 Y,Helmet_1 - 1 Z,Helmet_1 - 2 X,Helmet_1 - 2 Y,Helmet_1 - 2 Z,Helmet_1 - 3 X,Helmet_1 - 3 Y,Helmet_1 - 3 Z
Frame,,,,,,,,,,,,,,,,,,,,,
1,0.00,1396.537,-214.347,871.381,853.281,421.981,700.592,1695.296,-151.634,311.494,...,700.189,6338.134,586.469,1878.002,6102.620,535.364,1819.047,6401.660,379.448,1845.361
2,0.01,1396.539,-214.431,871.459,853.263,421.924,700.591,1695.309,-151.614,311.480,...,700.279,6338.754,586.201,1877.999,6103.292,533.905,1819.922,6403.273,379.573,1845.060
3,0.02,1396.569,-214.387,871.384,853.279,421.936,700.567,1695.281,-151.636,311.488,...,700.227,6339.407,585.921,1878.061,6104.045,532.485,1820.776,6404.934,379.663,1844.702
4,0.03,1396.522,-214.303,871.428,853.302,421.966,700.596,1695.295,-151.642,311.497,...,700.190,6340.158,585.700,1878.135,6104.754,531.045,1821.585,6406.563,379.794,1844.293
5,0.04,1396.523,-214.298,871.430,853.270,421.926,700.568,1695.292,-151.613,311.480,...,700.210,6340.856,585.441,1878.073,6105.649,529.621,1822.465,6408.240,379.899,1843.838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23853,238.52,1396.537,-214.652,871.576,853.341,421.903,700.478,1695.438,-151.656,311.464,...,700.184,4844.397,126.037,1860.752,4993.440,-32.378,1837.047,4658.483,-20.204,1787.414
23854,238.53,1396.535,-214.659,871.551,853.343,421.967,700.516,1695.428,-151.646,311.452,...,700.210,4838.280,119.167,1862.604,4987.573,-38.966,1838.069,4652.360,-27.452,1790.327
23855,238.54,1396.587,-214.661,871.556,853.324,421.921,700.543,1695.436,-151.676,311.496,...,700.160,4832.322,112.183,1864.237,4981.692,-45.657,1838.702,4646.233,-34.690,1792.938
23856,238.55,1396.555,-214.645,871.536,853.290,421.903,700.490,1695.441,-151.665,311.458,...,700.183,4826.375,105.228,1865.604,4975.922,-52.287,1839.261,4640.192,-42.065,1795.396
23857,238.56,1396.559,-214.669,871.541,853.287,421.913,700.521,1695.452,-151.693,311.505,...,700.192,4820.357,98.253,1866.723,4970.009,-59.002,1839.546,4633.981,-49.338,1797.427